### ISSUE TITLE
Remove Articles

### ISSUE THREAD

**Issue by jdsimcoe** [cleverdevil/indiepaper#7]
Is there an API (or a way) to remove articles from Indiepaper?

**Comment by EdwardHinkle** [comment]
Since IndiePaper sends a Micropub request to another server you would remove the post through whatever means the server supports. 
If it’s a Microsub Server like Aperture, you can delete posts using a Microsub client. 
If it’s a Micropub Server you would use whatever methods the Micropub server supports to delete the post.

(Originally published at: https://eddiehinkle.com/2018/07/27/1/reply/)

**Comment by cleverdevil** [comment]
As Eddie said, this is out of the scope of Indiepaper. Once an article is saved by Indiepaper to your target Micropub server, you'll have to use its API to remove articles from it.

If you're using Aperture, you can definitely remove articles using the Microsub API, or the Indigenous or Monocle Microsub reader clients.

**Comment by jdsimcoe** [comment]
Awesome, thanks @EdwardHinkle and @cleverdevil. I'm new to all this so thanks for explaining it. I'm currently using Micro.blog as my Micropub server, so it looks like I will have to wait for Micro.blog to offer feed management support.

**Comment by cleverdevil** [comment]
No worries @jdsimcoe! Make sure to share with @manton that you'd like some form of management of the saved items at some point.
